# Generated by Django 3.1.2 on 2022-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
