version: "3.9"

volumes:
  pgdata:

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "netology_stocks_product"
      POSTGRES_USER: "yakummi"
      POSTGRES_PASSWORD: "test123"
    expose:
      - 5432
    ports:
      - '6778:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yakummi -d netology_stocks_product"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 
    restart: unless-stopped
    volumes:
      - ./logs:/var/log
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 6777:8000
    depends_on:
      - postgres_db
 
